### ISSUE TITLE
MacOS does not launch Jetbrains Client

### ISSUE THREAD

**Issue by Moulick** [github/codespaces-jetbrains-feedback#10]
**Description** : MacOS does not launch Jetbrains Client
**Steps to reproduce** : 
1. Launch Jetbrains Gateway
2. Connect to GitHub codespaces
3. Error screenshot attached
**Impact** : Impossible to use GitHub Codespaces with Jetbrains Gateway

**Additional context**

1. https://youtrack.jetbrains.com/issue/GTW-2325/MacOS-complains-about-Jetbrains-Client-20223-EAPapp-being-damaged

```
OS Version: 13.1
OS Architecture: aarch64
IDE Version: 2022.2.4
Plugin Version: 0.2.0.896
Plugin path: /Users/moulick.aggarwal/Library/Application Support/JetBrains/Toolbox/apps/Gateway/ch-0/222.4459.11/JetBrains Gateway.app.plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway
```
![image](https://user-images.githubusercontent.com/15780903/201166875-ec1af645-57a7-47cf-b81c-7a9e77936fd5.png)

**Comment by cmuto09** [comment]
Hey @Moulick- thanks for the report! This is a known issue in Ventura, and JetBrains is working on a fix.

In the meantime you can follow [these instructions](https://github.com/github/codespaces-jetbrains-feedback#macos-13-ventura) to resolve the issue. You should only have to do it once, and it will work after that

**Comment by Moulick** [comment]
yep, the workaround works. Leave issue open till fixed?

**Comment by cmuto09** [comment]
> yep, the workaround works. 

Great!

> Leave the issue open till it's fixed?

Yep- good call. Thanks!
