### ISSUE TITLE
NullPointerException while using JetBrains Gateway plugin

### ISSUE THREAD

**Issue by oiiakm** [github/codespaces-jetbrains-feedback#103]
**Description**

I encountered a `java.lang.NullPointerException` while using the JetBrains Gateway plugin. It seems to be related to a casting issue. 

**Steps to Reproduce**

1. Open the JetBrains Gateway plugin in the IDE.
2. Perform a specific action or trigger a certain behavior.
3. Encounter the `java.lang.NullPointerException` error.

**Impact**

The `java.lang.NullPointerException` error disrupts the normal functionality of the JetBrains Gateway plugin. It prevents me from using specific features or performing certain actions.

**Additional Context**

- Operating System: Windows 11.0 (amd64)
- Java Version: 17.0.6
- IDE Version: JetBrains Gateway 2023.1.2
- Plugin Version: 0.4.0.1222
- Plugin path: C:\Users\AMIT KUMAR\AppData\Roaming\JetBrains\JetBrainsGateway2023.1\plugins\github-codespaces-gateway

**Error Stack Trace**

**Comment by thomas-sickert** [comment]
Hey @oiiakm, is this the same NullPointer as the one in this thread? https://github.com/github/codespaces-jetbrains-feedback/issues/101#issuecomment-1553887533

**Comment by oiiakm** [comment]
Yeah @thomas-sickert it is the same thread #101
