### ISSUE TITLE
Codespaces provider is not available on the latest JetBrains Gateway 2023.3

### ISSUE THREAD

**Issue by moznion** [github/codespaces-jetbrains-feedback#129]
Ref: https://youtrack.jetbrains.com/issue/GTW-7081/JetBrains-Gateway-doesnt-show-the-GitHub-Codespaces-provider

A support person Gyulnara Nevezhina said "GitHub didn't update their integration plugin to the 2023.3 compatible version. Unfortunately, we can't provide any ETA because it's an external provider. I guess it may be useful if you contact them as well.", so I report it here as well.

**Comment by doogle-oss** [comment]
Yeah this is not working with 2023.3
![image](https://github.com/github/codespaces-jetbrains-feedback/assets/1910577/259585ec-c063-4244-b6b7-ee88ed73c726)

**Comment by moznion** [comment]
This issue should be discussed here: https://github.com/orgs/community/discussions/78982
Because this repository was abandoned, according to #116, let's move on.

**Comment by fuzemobi** [comment]
@github-staff - Will there be any update to support this plugin or should we all move to JetBrains Spaces or Gitpod?

**Comment by fclante** [comment]
This is a major showstopper for our company in regards to using Github CodeSpaces. Is there any prognoses of when this is getting some attention?

**Comment by wiselancer** [comment]
The same issue with the latest version 2024.2.1
