### ISSUE TITLE
GitHub Codespaces Feedback: client app is damaged and can't be opened.

### ISSUE THREAD

**Issue by IRus** [github/codespaces-jetbrains-feedback#31]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/493656/202800616-329c440d-7487-41e0-a3c9-3abccbb4298c.png">

**Description** 
**Steps to reproduce** 
**Impact** 
**Additional context** 
```
OS Version: 13.0.1
OS Architecture: aarch64
IDE Version: 2022.2.4
Plugin Version: 0.2.0.896
Plugin path: /Users/yoda/Library/Application Support/JetBrains/Toolbox/apps/Gateway/ch-0/222.4459.11/JetBrains Gateway.app.plugins/github-codespaces-gateway
Plugin ID: com.github.codespaces.jetbrains.gateway

```

**Comment by thomas-sickert** [comment]
Hey @IRus, sorry for the friction. There's currently a known issue with ventura that's causing this problem, please check out the instructions [here](https://github.com/github/codespaces-jetbrains-feedback#macos-13-ventura) to work around it.

**Comment by IRus** [comment]
@thomas-sickert I figure out that I'm actually using stable version of Gateway, updated to EAP and now it works fine with Codespaces.
