### ISSUE TITLE
Can't connect to Codespace on Fedora

### ISSUE THREAD

**Issue by byquanton** [github/codespaces-jetbrains-feedback#6]
`failed to connect to Live Share: error connecting to ssh session: error creating ssh client connection: ssh: handshake failed: ssh: unknown key algorithm: rsa-sha2-512`

**Comment by shayneburgess** [comment]
Can you [verify your ssh key setup](https://github.com/github/codespaces-jetbrains-feedback#ssh-connection-issue) using the steps in the common issues section?

**Comment by carlosthe19916** [comment]
I was about to report the same issue but I've found this one. Nothing to add other than I have Fedora 36 and I have exactly the same error

**Comment by cmuto09** [comment]
Hey @byquanton and @carlosthe19916- we recently released a few updates that should make the SSH connection experience more reliable (plugin version `0.3.959` or later). 

You can follow [the steps here](https://github.com/github/codespaces-jetbrains-feedback#transitioning-from-the-alpha) to use that approach. Technically it will be using a different SSH key than the one you've listed above as we haven't added support for this algorithm specifically. 

Will this work for your needs, or do you specifically need support for SSH keys generated with the `rsa-sha2-512` algorithm?

**Comment by byquanton** [comment]
I've updated the plugin, but the error persists. It looks like that the plugin still uses the `rsa-sha2-512` Algorithm, and that Algorithm isn't enabled/supported on Fedora.

**Comment by velovint** [comment]
Doesn't seems like this issue is related to the codespaces plugin. I simply created a codespace from codespaces-examples/base and then simply `gh cs ssh` to it. My default key is ed25519. Debug file is empty.

> [vitali@fedora codespaces-demo]$ gh codespace ssh
> ? Choose codespace: codespaces-examples/base (main): reimagined broccoli
> failed to connect to Live Share: error connecting to ssh session: error creating ssh client connection: ssh: handshake failed: ssh: unknown key algorithm: rsa-sha2-512

There is also https://github.com/cli/cli/issues/4731 which seems related, although I'm not sure what to make of it.

**Comment by xperimental** [comment]
While trying to debug the issue by running `gh cs ssh` in the debugger, I was surprised to find that the version compiled by myself (of `gh`, _not_ the IDE plugin) does not have the same issue and I can both use it on the command-line without issue and when I let Jetbrains Gateway use the self-compiled version of `gh` it is also able to connect to the Codespace fine.

I have not yet found out what the difference between the publicly available version `2.20.2` of `gh` and my self-compiled version is. I compiled my own version from the `v2.20.2` tag, so they should be similar. So while it is not a solution to this issue yet, it might at least be a workaround.

**Comment by gucio321** [comment]
the problemm still exists for me... any updates here?
```console
[~ (130) ]$ gh cs ssh
? Choose codespace: gucio321/tic-tac-go (master): stunning zebra
failed to connect to Live Share: error connecting to ssh session: error creating ssh client connection: ssh: handshake failed: ssh: unknown key algorithm: rsa-sha2-512
[~ (1) ]$ 

```

**Comment by byquanton** [comment]
Updated the gh cli today and it started working (https://github.com/cli/cli/releases/tag/v2.22.0)

**Comment by gucio321** [comment]
yes, I can confirm that after upgrading to `gh version 2.22.0 (2023-01-25)` it finally works

**Comment by xperimental** [comment]
I just tried again and noticed that it still was not working for me on `2.22.1`. Then I wondered what the difference is and realized that I was kind-of on the right path in my last comment but "in the wrong way". I failed to realize before that I installed `gh` from the Fedora repository (`2.22.1-1.fc37`) instead of from the release RPM downloadable in this repository.

So, I guess this needs to be a bug on the Fedora package instead. I'll try to get this sorted in the next days, but if there's someone already aware of the necessary process feel free to take over. :slightly_smiling_face:

**Comment by TrevorBenson** [comment]
> I just tried again and noticed that it still was not working for me on `2.22.1`. Then I wondered what the difference is and realized that I was kind-of on the right path in my last comment but "in the wrong way". I failed to realize before that I installed `gh` from the Fedora repository (`2.22.1-1.fc37`) instead of from the release RPM downloadable in this repository.
> 
> So, I guess this needs to be a bug on the Fedora package instead. I'll try to get this sorted in the next days, but if there's someone already aware of the necessary process feel free to take over. slightly_smiling_face

https://bugzilla.redhat.com/show_bug.cgi?id=2175969
