### ISSUE TITLE
Is there an option to make a local machine port available in the container

### ISSUE THREAD

**Issue by motorro** [github/codespaces-jetbrains-feedback#69]
Hello!

I wonder is there an option to make a port on the machine running the Gateway available to the container?
Similar to `-R` argument on `ssh` instead of `-L` (port reversing that is AFAIK)

I'm trying codespaces for android development and want to be able to connect remote Intellij Idea to a device attached to the local `adb` server.

- The `adb` server runs on the developer machine
- It scans locally connected devices
- Exposes them to `adb` clients

So if the `adb` 5037 port is available to Idea running on a server I could use it to debug the application (potentially)

[More](https://developer.android.com/studio/command-line/adb) on how `adb` works

**Comment by cmuto09** [comment]
Hi @motorro! I don't believe there is a built-in way to achieve this type of connectivity (forwarding a local port to the Codespace itself). Howver I believe that you could achieve this through Tailscale. [Here's some documentation](https://tailscale.com/blog/github-codespaces/) on getting tailscale installed and working on a Codespace. Once installed and configured properly on both your codespace and your local machine, I believe the tailnet can support the type of connectivity you're describing
