### ISSUE TITLE
Not loading on beta version of Gateway

### ISSUE THREAD

**Issue by SageSphinx63920** [github/codespaces-jetbrains-feedback#90]
Hey,
im using the beta version of gateway and the plugin doesn't load anymore, because its wrong configured. I don't know if this is intended behavior or just a bug

**Comment by thomas-sickert** [comment]
Hey @SageSphinx63920, thanks for opening a ticket! 

That's intended. The supported versions of the gateway are `223.*` and the beta is `231` currently. We'll be adding support for newer versions of the gateway in the future. In the meantime, you can use the release version of the gateway with the plugin to continue using Codespaces with JetBrains IDEs.

**Comment by SageSphinx63920** [comment]
This for your answer! I'll just use the release version until the plugin is updated
